### ISSUE TITLE
Datasets and models disappear

### ISSUE THREAD

**Issue by shaoyuyoung** [Mohammad-Abdul-Hadi/PTM-API-Learning#1]
Hello,

It seems that datasets and models which are in Google Drive are missing.

Can you resubmit them？

Thanks in advance!

**Comment by kongmoumou** [comment]
+1 @Mohammad-Abdul-Hadi

**Comment by Mohammad-Abdul-Hadi** [comment]
@kongmoumou and @shaoyuyoung,
The dataset and models had to be relocated due to Google-Drive space issues. I am working on putting them on Huggingface. It may take some time as I am busy with other projects, which unfortunately also demands the limited space in my drive. Meanwhile, you may access the dataset from the following link: https://drive.google.com/drive/folders/1jBKMWZr5ZEyLaLgH34M7AjJ2v52Cq5vv
Thanks for the patience!

**Comment by kongmoumou** [comment]
@Mohammad-Abdul-Hadi Thank you for your reply~ I've been working on a related problem recently and very interested in your work. I would like to use your trained fine-tuned model for comparison. Could you upload it to dropbox or zendo if Google-Drive is unavailable? 🥺

**Comment by Mohammad-Abdul-Hadi** [comment]
Sure, @kongmoumou.
Right now, I am at the middle of something and close to a deadline. I will notify you and update the README.md as soon as I can upload it somewhere.

**Comment by kongmoumou** [comment]
Awesome, thx a lot~ 👍

**Comment by shaoyuyoung** [comment]
Thanks a lot

**Comment by kongmoumou** [comment]
@Mohammad-Abdul-Hadi Hi 🤣~ You may have forgotten due to your busy schedule, and I'd like to remind you to update the model link if you have some spare time.
